apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane

resources:
  - compositions.yaml
  - namespace.yaml
  - providers.yaml
  - provider-config.yaml
  - xrds.yaml
  - functions/builtin-objects.yaml
  - functions/go-templating.yaml
  - https://doc.crds.dev/raw/github.com/crossplane/crossplane@v1.18.2 # renovate: github-releases=crossplane/crossplane
  - https://doc.crds.dev/raw/github.com/crossplane-contrib/provider-keycloak@v1.11.0 # renovate: github-releases=crossplane-contrib/provider-keycloak

helmCharts:
- name: crossplane
  releaseName: crossplane
  namespace: crossplane
  repo: https://charts.crossplane.io/stable
  version: 1.18.2
