ingressRoute:
  dashboard:
    enabled: false

service:
  type: LoadBalancer
  spec:
    externalTrafficPolicy: Local
    internalTrafficPolicy: Local
    loadBalancerIP: 192.168.0.90

providers:
  kubernetesIngress:
    publishedService:
      enabled: true
      pathOverride: "traefik/traefik"

ports:
  web:
    expose:
      default: false
  websecure:
    asDefault: true
    expose:
      default: true
    exposedPort: 443
    tls:
      enabled: true
    middlewares:
      - traefik-securityheaders@kubernetescrd
    transport:
      respondingTimeouts:
        readTimeout: 0 # Required for Netbird signal GRPC
  webpublic:
    expose:
      default: true
    port: 9443
    containerPort: 9443
    exposedPort: 9443
    tls:
      enabled: true
    middlewares:
      - traefik-securityheaders@kubernetescrd
    transport:
      respondingTimeouts:
        readTimeout: 0 # Required for Netbird signal GRPC
  ssh:
    expose:
      default: true
    port: 2222
    containerPort: 2222
    exposedPort: 22
