apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
- name: proxmox-cloud-controller-manager
  releaseName: proxmox-cloud-controller-manager
  namespace: kube-system
  repo: oci://ghcr.io/sergelogvinov/charts
  version: 0.2.11
  includeCRDs: true
  valuesFile: values.yaml
