apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: csi-proxmox

resources:
  - namespace.yaml

helmCharts:
- name: proxmox-csi-plugin
  releaseName: proxmox-csi-plugin
  namespace: csi-proxmox
  repo: oci://ghcr.io/sergelogvinov/charts
  version: 0.3.1
  includeCRDs: true
  valuesFile: values.yaml
