---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-password
  namespace: keycloak
spec:
  encryptedData:
    password: AgBgtRvU9pbVKgL7wZQnogcTXA+I8XO3BqAzialWSeeX3YpYCBbhNELkTe4BcugoYfL+keC/0D2VqiECisYL4arvUkOmHXKBVUsl97rzSKcS8zSomy4OMx3lQWI6xBuB4vwLzDN6qcl+LfnoIJlzcycpgQhdWPPcEJ3utzp/dhO9LzocCW2xHREgaySYSkuaTBdq/Tj2HZKuaJ7hVNgbO00zjHZd7qAs0OVFoZpJlZyMYdZU0S1r0gL+XaP3v2ARZ3XQEDmmxufLOPWcxYOeJ712q8wFZn5sCJdns31sFCFYI5mN/d6iBvcEfuWLnCz1ET0DC6HgedLID1jB3sCjYnQdz92V2fkDyj6uzqb7X9CTKwn6JvY8Egd40KVbamsLuoiT2aNpFw23gkK3Ajus3H5S9aL3k8zCSgBrHBKkO2TZDER6Fzw39cLBSnRBWzPS7wy10JIfRNPKV9rmGlHWY6y+H4KWkPiIlUOqDGjlfaLPXyD9o0DcTs3rTPF/lScqPtqSlKJCEDwWqudC8UKLn5YSPfECdOnqNCDyj586h+FZk0IxU4MSG7HbLHi+B3/Aev3qibBeMIYSsUYGn+B61YY0INm+AEV+M2Co98WU46S7+zIHpxSK6LxV+ov6MIdyo1tGC4PnFd1bIZ2ZxjlUnwMfE8tFSyWO+963ECVcPx0rXbvEDnzKvPsW4f25ttk0zzjX2WLxOfs6fcOKnoeGnG+U
  template:
    metadata:
      name: keycloak-admin-password
      namespace: keycloak
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-initial-password
  namespace: keycloak
spec:
  encryptedData:
    password: AgAh73gywqf2fP3OPwTeS3Dsw8mPr2cUc16Y9Lqrt6L6jbsL7Y8S3wAl4t3KhmtkEKxrRWwwK+D9TJPayAwmWYlqYwD5DhE1U9Yag8ZJkMlJOMjVsTGBWDScTSy/tJwHEtfD+rmo9HEjLY1sfdczmr94PygosHJvmrMFWO2YnZEvyKTXz0e+BPytcGOCh7/hd9t0c79VHDN0HZbd8hiHW3eVzQj2kv37X57H1iJx3XVI+53Vj1JJ/RZ9pM0CXanc1LyhGHhi0g5nokstwUXC/QgTEVqe76AC4EiyKVQ91dp7b5OsJvNRhsQy4u85C1GBANiDrxFBHmCbyn3JP2+yixjw5MvGCCGkD45dj2O5JrprGd7EmmBxfTMTYFc7j8BkTe0vcepfF80dDPr736dGHKc7VoB7mz9swFyhu+EIyS6ss0WwBRMNSwyUe+e/kbrp7SKYXyAKr+9mU/7DWnpcoek/JJsVfNvaF6QSVY7eqwsMmKXFkeqtGA0MdBiz9kKhg/NZmFGuerxAM8o1U7MpP7H+VKPW7zSQu9W+UTF4cJy3hP6PaCPduysvk5T7n+IvBbnhvlD8Db/KIF0gjpmp3E2mcPFVifEPIvLVtXbwjElRQVqLqS/69WK6JV8HriBfzIMPiiIklwCds6yUZQQKKCraHjTquj6KMib/wEsgFrbHkuKPAr8BIBkuuM/UCgf/loNFlB7vUrYtfhM=
  template:
    metadata:
      name: keycloak-initial-password
      namespace: keycloak
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak
spec:
  encryptedData:
    password: AgA+ujL86YIs5ecAexMZ/CgsEBN5VMSYoXV2C0+OKEbmlaNwqBDzlTbFiCMBLe+RIaLTbJ5Lj14HFrGWqx4SdKpIqwJwxtzYJqnUzsQmgHQrAg17OJHgZbMdtI01F13/LrPjaLi0dmygPzO6xw1/bw8RHd1GiAeVorUmQh0Z7zfw33x3YaSb/KC4lCyn+INYOrPG+Gl7WtwKe0g7lLQbkwIl89A37SGHABxErlmuecev6j8CDNQ/WGugHrz/WJK6Z4bNIItMSi0YUeSL60LniEF9Vdx8FrEZ/VMMvyzHz9Sy8X1ygcTKnQi2woKi8QIXi0t1yRAj9HNHmtojh6iDvFtQVldX+OGmCb52iwaS1gybmzPXEs+++vRG1btosXh2t2PGs0SeCvZul+ZVufOfB/i9pRuu6AvVOAqxGz2Z1bRinZfkbrYlweUv5GwZKFTb+xRBx5Umwv1jJ/zngCEEZ+xdAk5iC6IVhqfclW8qcESagEPgIK0ZPwD7KD2iLi9dy3Ob0nd8+jvlnIr1BmwoPc5pf+mbt50OpGAdMlBGfPaYRFFM95pFs3UEX/E0gM/RRWDzgz8c60fyvnV9ACeRLnDqQhMUp3G8z7P6ZndnvVRw9R1n0mXR7yUabUtju63/tHQpY9muJ0m7occD93W+18mUVDPoiBC/sQzppYtqBNo/CJ96L2D0wky/raUNKQQVaiYw/izlXIquW6kn
    postgres-password: AgChWk610AN5uWVgF6/DlIZZ/GJSFfUZi8s0VPluyo6/iT8yKahc1wWW2hnQ2CIfHAlziq/ksLWElPAgpFYSaQAcOLi/uOEi8K4tR994MAMYMX8zh46ZOm4e7da8E8kS7A96aez2cs5J19VPoGbEwteCqB+sZFby+4qLeRPTL6Fk0q8WppnhZDstYwvMYL2gpTeIDqQlwyg360QTHoFa7BAntdpJcO3eA11tTubhV16ImwV348LYo4x1o5fesgazepAope2KhujKuPjBjqEDfMObJUvTTQuXQswmVLG7N4eeBilo/CEAWt7JS4wDODQM1RxLjiySDqJJBjwKxISORX19Np1iPINmTuJddCiS+i4xo6qp25SbExx9AT94TW6bSZrAruJsPPrm30tc90/nGBRnM/kD0CtfOayudmrkli3NMm4fAJ+qWaNTaU4WAiy0jimO5BrPzK+OlCVR7VRh2r6nr83X4BHAYjY7cAiCNF9ptl4G3EKvYnMawM5I3pGCbyr+0XbihEXurphFso5ElvmhzDonv/rzLF+ta/frpYdN2o2I7UUamh+is6u3iYFl/Zh+k8eZuJxZkdY/h2pha5ZL9tjzniGFQxYbWqMZN5suZDBo/YtItHlhx8Jr1o3m7lwpW299P11DFoo8rPHPUfOxTet9iqCDHTTBGx8ymLqG1fnT91WbJP+JIFHY8O9+HnrY2+Wg5aGpDkg9
    username: AgAPDXqoidAyFnMjYy6AHu9w/IS/IyQF7EjGtb3kFaq86nTLvtdSPBgS2V1cEi/Ko8MI8e0B0TA6LfXfvFm85yTDzazGVCRWVDLWBdrt5FEKqg/gUbBZXvC/AcBCxMZxE+cXXLuICz5ogW0Z+nDhgo343IUTG9QgWKXVPVpp2IPqI7ka0IhwbBo9/Q7kd2UwkMDxzNIqgArr/l25fZ59YsjvASI9qFh6rsnSu4idsLGRFJwo5oKJMUVM1K4BaFz5fllBKijTvueLP1FyOMzYjA3DUdu4fr6dmqbZTZu8pzDr4AJdNsYTN54vaZj6+46DHPH29iSYHYHRMGvk4KcJsIOibTxlIxiXS+WzwuaVfPkdAYFwR0vcuBplsFG0yxhNA//bQCtMQIteF3ofGgLtSXdibaXstkuHCCvWR6Mg4/zN/xuDt5qrQW/cPepjKgxqWSObF95BKKp0Tv9fID1K4MlRLI4g+k6j/nMr8hli7ZMtoaQLUa26nnQU9V7dwK/r6GdgCPVtO1gHm5XPL8z4HB5pa7/pxQdieCHLBV9+TFSaEqxhDReje2ZyeLFehQEYdBqEarxqe8L/CNZIQPPzkDNn6X2qmpPiQFiraBOkYB1Q2yr0j5nj6Xuv1ObGlMCvo4fDVW4aWcOquu4IDL2J7nZkON6qbDnMHVoq7/cif8Pf448lA5iqzTRMIGeUlq31EigqJ2g7LNNGGHmUCQ==
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crossplane-keycloak-credentials
  namespace: keycloak
spec:
  encryptedData:
    credentials: AgBTjhI8iY1NIToAtBAbRe9qVikwtCVKzH52DYazQICVjjHOBOmG+XHQ0XSnopit6le+ayC9ls2pp3zRMXacMyd6a9x5qmFcO9N0hTxPa9F9O2tuwAjUBaWWegM+WgMu2DXa/9nYdKi0Kz1HSDy0gnB9Wtlmd4Xjbr/tYpDRVTRKizCgs1LLNr7/o6G/ZV0zrJH0Hxt85cZNPjSIoODu4v69ea/Xq8ioqSC6GvfThFQdwx1CZi/TS1OAHarpSWl+i3RfPEls46iLNhHi3t8tD1YumSCENqpFtQ3B1jMc5kAE4kGtsvA9RdrGp8oDLIurmWOzL7HeYSJILrB6cVo7L+Y9wnI+ovCeyqbHeGIjBnYUUYTW7kvubbhBzzdhwDDVsUk5/3TYV8eQoccvYWPfmOhzIGEmBH7jOdD7TfCvbx1TMv2cuMjTGoE2A0WBE+hHY/OgtlWN+Mgvld83KvMLW8cNp2Q4ZhY+syo5okgkAUUqUbsw17bGpBnGObsipdB2j/PqqGTHlNcqskK46TVsu8MPV2MwWcZ/UfDbiEyA9GVYFB8aZXtoNwhXsRLNVS874K3HbtiMoNNWYaZ3ddairQl8uomhEm/H/33IiRJwElFgKfQvQOr5ak6yoBC75NoFetz4fZLr0XgWgB2RvIckb3+WxjrCmc5IdrlrL221otu70T1bZcvZN1vaDA9V2AseY7/WZJuGDqHpfeARkdXzDJd99LPW1Ww6eGBru1BQQWi0obilE+dVEueJ9neebkmZX07OTU1dOQRVvHFQb7k0U39s646mseV5g62d5J+2dnxE9bwoYdy9XY2Hu/oCqPW3ezgyENy0rjwhJo3ua36P2BSkDGI694N7EEb2GjuZSZKlDCWaAmfEGhj4Fw9z
  template:
    metadata:
      labels:
        type: provider-credentials
      name: crossplane-keycloak-credentials
      namespace: keycloak
    type: Opaque
