apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ollama

resources:
  - namespace.yaml

helmCharts:
  - name: ollama
    releaseName: ollama
    namespace: ollama
    repo: https://otwld.github.io/ollama-helm/
    version: 1.5.0
    valuesFile: values.yaml
