apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - announcement-policy.yaml
  - ip-pool.yaml
  - https://doc.crds.dev/raw/github.com/cilium/cilium@1.17.1 # renovate: helm=cilium registry=https://helm.cilium.io

helmCharts:
  - name: cilium
    releaseName: cilium
    repo: https://helm.cilium.io
    namespace: kube-system
    version: 1.17.1
    includeCRDs: true
    valuesFile: values.yaml

patches:
  - path: patches/delete-hubble-tls-job.yaml
